### ISSUE TITLE
[Question] How Much Work to Implement as a Lightwieght Substrate Validator Node?

### ISSUE THREAD

**Issue by zicklag** [paritytech/smoldot#2118]
Hey there!

I'm thinking about using smoldot to run a substrate validator node for a custom chain I'm building. I want the node to use as few resources as possible so that other apps running on the server aren't effected, which seems to be somewhat in-line with the smallness focus of smoldot.

According to the docs, the block authoring hasn't been implemented yet, and I've seen that off-chain workers haven't been implemented yet either.

If I was fine without off-chain workers and I just needed Aura and GrandPa, do you think it would be difficult to add to smoldot. I would be trying to learn how to port the implementation from substrate, but if it's something that you think would be rather challenging, I might just be better off trying to slim down a substrate node, instead of building up a smoldot node.

I'd be grateful for any perspective you have on which option might be more feasible.

---

My more precise use-case is to run a blockchain as a systems orchestration "database". Each node in the server cluster would run a blockchain node that it would use to determine the server's desired state, and to push updates about it's own state to the chain where necessary.

Because the nodes in the cluster are meant to run other apps, I want the blockchain node to avoid using as much disk, CPU, and memory usage as possible. I don't need the full block history for instance, so I like the way that smoldot prunes all blocks other than the latest finalized block.

**Comment by tomaka** [comment]
Hey!

> I want the node to use as few resources as possible so that other apps running on the server aren't effected

I just want to mention that the more transactions per second your chain has, the more resources a node must use. It's inevitable. A node must verify that every single transaction on a chain is valid, sometimes multiple times (once before the transaction is in the chain, then one or more times after it is in the chain).
If your node doesn't have enough CPU, it will simply be unable to follow the chain and will fall out of sync.
Running a full node on a low-resources machine, while it works for small chains, is in general not really the greatest idea.

> I just needed Aura and GrandPa, do you think it would be difficult to add to smoldot.

Unfortunately yes. Grandpa is a huge beast. Aura partially works.
Beyond Aura and Grandpa, there are tons of things in smoldot's code that are left unimplemented (but kept track of) intentionally due to the fact that full nodes aren't really supported.

> I might just be better off trying to slim down a substrate node

It might sound obvious, but it's not intentional that Substrate is big. If we knew how to easily slim down the node we would do it.

Substrate is extremely complicated, not just in its implementation but also its protocol. Both slimming down Substrate or building up on smoldot are extremely complicated.

> I don't need the full block history for instance, so I like the way that smoldot prunes all blocks other than the latest finalized block.

The fact that smoldot prunes all the blocks except the latest finalized block is the case only for the light client.
In a full node situation, if you discard every block except the last one, any node that disconnects and falls out of sync will be unable to catch up. The only way you can prove that a block is valid is by verifying the entire chain, and if you get rid of the older blocks in the chain, you can't prove that anymore.
There are ways to generate a proof other than by verifying every single block, but they're not implemented neither in Substrate nor smoldot at the moment.

**Comment by zicklag** [comment]
Thanks for the great response!

> Running a full node on a low-resources machine, while it works for small chains, is in general not really the greatest idea.

That's good insight. In my use-case there will likely be very few transactions by users, because only system administrators can interact with the cluster, but I haven't done a thorough evaluation of how many automated transactions will be submitted by nodes in the cluster, so that's something I have to think about.

> It might sound obvious, but it's not intentional that Substrate is big. If we knew how to easily slim down the node we would do it.

That's a good point. I was thinking along the lines of simple things like configuring the block pruning and maybe trying to get aura to not generate blocks when there are no transactions ( I haven't explored this yet, just had the thought ), or finding other things that I may not need that might be included by defAgain, thanks for the insight. ault.

> There are ways to generate a proof other than by verifying every single block, but they're not implemented neither in Substrate nor smoldot at the moment.

At this point I'm wondering if a full blockchain is more resource intensive by nature that what I'm hoping for in my use-case. Sounds like I've got more investigating to do, but I really appreciate your input. Thanks again for the help!
