### ISSUE TITLE
Improve initial sync time

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2590]
I want to use this for AWS Lambda but the initial sync time make it is not really suitable.
One possible solution is provide the ability expose syncing state to allow the application to persist it and reload it on next run to reduce duplicated work.

This could be out of scope so feel free to close this. Alternatively I will just need to run a long lived client in another server.

**Comment by tomaka** [comment]
> One possible solution is provide the ability expose syncing state to allow the application to persist it and reload it on next run to reduce duplicated work.

This is actually possible, but only with smoldot and not substrate-connect. There's a `databaseContent()` method on a `Chain`, and you can pass back this database content to the options when calling `addChain`.

https://doc.deno.land/https://deno.land/x/smoldot@light-js-deno-v0.6.27/client.d.ts/~/Chain
https://doc.deno.land/https://deno.land/x/smoldot@light-js-deno-v0.6.27/client.d.ts/~/AddChainOptions

**Comment by tomaka** [comment]
The reason why it's not possible with substrate-connect is that it creates problems and ambiguity.
For example, what if you a web page passes a wrong database (with a correct format, but containing wrong information)? Since the extension is used by multiple web pages, it can't just trust the database sent by a random web page.

The difference between substrate-connect and smoldot is really just the browser extension, and in your use case, since you're not running the light client in a browser, using smoldot directly is in principle more appropriate.
Unfortunately, PolkadotJS isn't wired to use smoldot directly.

**Comment by xlc** [comment]
Thanks for the pointer. I will try to use smoldot directly and see what will be the best way to connect polkadot.js with smoldot. In any case, this issue is resolved.
