### ISSUE TITLE
Ability to provide alternative implementation of host functions

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2948]
required by https://github.com/AcalaNetwork/chopsticks/issues/13

I will start with some refactoring on [host.rs](https://github.com/paritytech/smoldot/blob/main/src/executor/host.rs), abstract the host handling code into a trait, move the current implementation to a struct, and then make it customizable.

**Comment by tomaka** [comment]
> abstract the host handling code into a trait

There are two traits in the entire source code right now, and it's because I had no other choice. If you open a PR that adds trait definitions, I'll likely refuse it. I don't want smoldot to turn into Substrate with its hundreds of incomprehensible abstractions.

If you explain what you would like to achieve, I can provide a code design for it.
If you just want to disable signatures verification, a simple `force_signatures_verifications_success: bool` field in `host::Config` suffices.

**Comment by xlc** [comment]
Ideally I want user to override host functions but I am ok to have this less generic at this stage.

So I will add a config `muck_signature_verification_host_functions`, when true, it will return true if the signature is valid OR if the signature is equal to a magic value.

**Comment by xlc** [comment]
closed by #2955
