### ISSUE TITLE
Initializing Polkadot takes a long time in the Wasm node

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#647]
It takes maybe around 20 to 30 seconds on my machine between `Loaded chain specs for Polkadot` and `Initialization complete`.

**Comment by expenses** [comment]
I managed to generate a flamegraph for this by putting the polkadot chain spec in `westend_specs.js`, removing `wasm-opt` from `prepare.js` (because it strips out debug symbols) and running `perf record -e cycles:u -g -- node --perf-basic-prof test/demo.js`.

![1615901700](https://user-images.githubusercontent.com/13566135/111318129-0c3bda00-8665-11eb-96fb-df01c5329d44.png)

**Comment by expenses** [comment]
https://github.com/paritytech/smoldot/blob/cbc065efcff09eec8d65fde531de70ddc653bc7a/src/lib.rs#L241-L244 seems to be the problem

**Comment by expenses** [comment]
> and running `perf record -e cycles:u -g -- node --perf-basic-prof test/demo.js`.

See https://nodejs.org/en/docs/guides/diagnostics-flamegraph/
