### ISSUE TITLE
Full node initialization very slow with existing database

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#678]
The full node initialization is currently extremely slow because it copies the entire storage in memory: https://github.com/paritytech/smoldot/blob/5b95d60892d1e2349af4b4e73e7bb7be60d4e199/bin/full-node/src/sync_service.rs#L140-L151

At the block where I am, the storage is only ~83 MiB but loading it takes a minute or two.

**Comment by expenses** [comment]
I wanted to test this out so I can the full node using perf and opening the database took a minute or two, but because of code in sled, not the code you link.
![1616762812](https://user-images.githubusercontent.com/13566135/112634037-647b9480-8e3a-11eb-893d-cd070037ec1a.png)

I then quit the node and ran it again, but this time it loaded in much less time. Does sled do any kind of decompression to disk?

**Comment by tomaka** [comment]
If the node shut down in an unclean way, reopening a database can take a lot of time because it has to go through the journal. This isn't really specific to sled and is a consequence of how databases are designed.

The issue I mention happens for me when I'm around Polkadot block 2 million. If I start syncing from scratch, I don't immediately have the slowness.

**Comment by tomaka** [comment]
Fixed by https://github.com/paritytech/smoldot/pull/689
